config/routes.rb
Rails.application.routes.draw do
  get 'galleries/new'
  get 'galleries/edit'
  get 'galleries/index'
  root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    # 新規登録画面のリロード時のエラー防止
    get '/users', to: redirect("/users/sign_up")

    resources :users, only: [:show, :edit, :update]

    post '/galleries/new', to: 'galleries#new', as: 'new_gallery'
    resources :galleries, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      get :marks, on: :collection
      resources :marks, only: [:create, :destroy]
    end

    patch 'travels/travel/:id/sort', to: 'travels#sort'
    resources :travels, only: [:create, :destroy, :index, :show] do
      resources :travel_plans, only: [:create, :update, :destroy]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mark.rb
class Mark < ApplicationRecord

  belongs_to :user
  belongs_to :gallery

  validates_uniqueness_of :gallery_id, scope: :user_id
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_gallery, only: [:create, :destroy]

  def create
    Mark.create(user_id: current_user.id, gallery_id: @gallery.id)
    render 'marks/mark'
  end

  def destroy
    mark = @gallery.marks.find_by(user_id: current_user.id, gallery_id: @gallery.id)
    mark.destroy
    render 'marks/mark'
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_mark.html.erb
<% if gallery.marked_by?(current_user) %>
  <%= link_to gallery_mark_path(gallery, current_user), method: :delete, remote: :true do %>
    <i class="fas fa-bookmark"></i>
  <% end %>
<% else %>
  <%= link_to gallery_marks_path(gallery), method: :post, remote: :true do %>
    <i class="far fa-bookmark"></i>
  <% end %>
<% end %>

app/views/marks/mark.js.erb
$('#mark_<%= @gallery.id %>').html("<%= j(render partial: 'marks/mark', locals: {gallery: @gallery}) %>");

app/views/marks/marks.js.erb
$('#mark_<%= @gallery.id %>').html("<%= j(render partial: 'marks/mark', locals: {gallery: @gallery}) %>");