config/routes.rb
Rails.application.routes.draw do
  get 'galleries/new'
  get 'galleries/edit'
  get 'galleries/index'
  root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    # 新規登録画面のリロード時のエラー防止
    get '/users', to: redirect("/users/sign_up")

    resources :users, only: [:show, :edit, :update]

    post '/galleries/new', to: 'galleries#new', as: 'new_gallery'
    resources :galleries, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      get :marks, on: :collection
      resources :marks, only: [:create, :destroy]
    end

    patch 'travels/travel/:id/sort', to: 'travels#sort'
    resources :travels, only: [:create, :destroy, :index, :show] do
      resources :travel_plans, only: [:create, :update, :destroy]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/travel.rb
class Travel < ApplicationRecord

  belongs_to :user
  has_many :travel_plans, -> { order(position: :asc)}
  has_many :gallery, dependent: :destroy

  validates :title, presence: true, length:{maximum: 10}
  validates :date, presence: true
  
  def start_time
    self.date
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:destroy, :show, :sort]

# user/show内

  def create
    @travel = Travel.new(travel_params)
    @travel.user_id = current_user.id

    @travel.save

    @travels = current_user.travels.all
    @selector = "#travel"
    @url = "travels/index"
    # travels/index.js.erbでindex.htmlを更新
    render 'travels/index'
  end

  def destroy
    @travel.destroy

    # 以下createと同じ
    @travels = current_user.travels.all
    @selector = "#travel"
    @url = "travels/index"
    # travels/index.js.erbでindex.htmlを更新
    render 'travels/index'
  end


# travels/show内

  def show
    @travel_plan = TravelPlan.new
  end

  # travels/_plansのposition更新
  def sort
    travel_plan = @travel.travel_plans[params[:from].to_i]
    travel_plan.insert_at(params[:to].to_i + 1)
    head :ok
  end


  private

  def set_travel
    @travel = Travel.find(params[:id])
  end

  def travel_params
    params.require(:travel).permit(:title, :start_time, :user_id)
  end

end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_index.html.erb
<div class="travel__index">
  <% travels.each do |travel| %>
  <div class="travel__item">
    <%= link_to travel_path(travel) do %>
      <%= l travel.date %>
      <%= travel.title %>
    <% end %>
    <%= link_to travel_path(travel), method: :delete, remote: true do %>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
  <% end %>
</div>

app/views/travels/_plans.html.erb
<div class="plan__box" id="sortable_list">

  <% travel.travel_plans.each do |travel_plan| %>
    <div class="plan__wrap">
      <div class="flex-center" id="bar">
        <i class="fa fa-bars"></i>
      </div>
      <div class="plan__item">
        <p><%= travel_plan.text %></p>
      </div>
      <div class="btn flex-center">
        <%=link_to travel_travel_plan_path(travel_plan.travel, travel_plan), method: :delete, remote:true do %>
          <i class="fas fa-times"></i>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= hidden_field_tag :travel_id, travel.id %>
  <%= javascript_include_tag 'travels/Sortable.min' %>
  <%= javascript_include_tag 'travels/sort_plan' %>
</div>

app/views/travels/index.js.erb
$("<%= @selector %>").html("<%= j(render "#{@url}" , {travel: @travel, travels: @travels}) %>");
$(".form").val('');
$(".error-messages").html("<%= j(render 'layouts/errors', model: @travel ) %>");

app/views/travels/show.html.erb
<div class="main__field">
  <h1 class="page-name"><%= l @travel.date %></h1>
  <h1 class="page-name"><%= @travel.title %></h1>

  <div class="travel__wrap">
    <div class="travel__form">
      <%= form_with model:@travel_plan, url: travel_travel_plans_path(@travel) , method: :post do |f| %>
        <div class="error-message"></div>
        <%= f.text_field :text, class:"form" %><br />
        <%= f.submit 'Add', class:"form__btn" %>
      <% end %>
    </div>

    <div id="plans_index">
      <%= render 'travels/plans', travel: @travel %>
    </div>
  </div>

</div>