config/routes.rb
Rails.application.routes.draw do
  get 'galleries/new'
  get 'galleries/edit'
  get 'galleries/index'
  root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    # 新規登録画面のリロード時のエラー防止
    get '/users', to: redirect("/users/sign_up")

    resources :users, only: [:show, :edit, :update]

    post '/galleries/new', to: 'galleries#new', as: 'new_gallery'
    resources :galleries, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      get :marks, on: :collection
      resources :marks, only: [:create, :destroy]
    end

    patch 'travels/travel/:id/sort', to: 'travels#sort'
    resources :travels, only: [:create, :destroy, :index, :show] do
      resources :travel_plans, only: [:create, :update, :destroy]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # emailのバリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter, :google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_many :travels, dependent: :destroy
  has_many :galleries
  has_many :marks, dependent: :destroy

  validates :name, length: { minimum: 1, maximum: 10 }
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }}

  attachment :profile_image

  def self.guest
    find_or_create_by!(name: "ゲストさん", email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end



  # SNS認証（登録済みuserかどうか）
  def self.from_omniauth(auth)
  sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create

  user = sns.user || User.where(email: auth.info.email).first_or_initialize(
    name: auth.info.name,
    email: auth.info.email
  )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
    authorization
  end

  def google_oauth2
    authorization
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to root_path
  end


  private

  def authorization

    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render "devise/registrations/new"
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      # パスワード生成
      pass = Devise.friendly_token[0,20]
      params[:user][:password_confirmation] = pass
      params[:user][:password] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(current_user)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
    if @user != current_user
      redirect_to user_path(current_user)
    end
      @travel = @user.travels.new
      @travels = @user.travels.all.page(params[:page])
      @galleries = Gallery.where(user_id: @user.id).all.page(params[:page]).per(2)

      # pagenateの非同期
      respond_to do |format|
        format.html
        format.js { render :action => "pagenate" }
      end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def set_user
    @user = User.find(params[:id])

    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_calendar.html.erb
<%= month_calendar events: @travels do |date, travels| %>
  <%= date.day %><br />
  <% travels.each do |travel| %>
    <%= link_to travel_path(travel), class:"title" do %>
      <% travel.title %>
    <% end %>
  <% end %>
<% end %> 

app/views/users/_user_gallery_index.html.erb
<h3>投稿記事一覧</h3>
<% galleries.each do |gallery| %>
  <div class="gallery__items">
    <%= link_to gallery_path(gallery) do %>
      <%= image_tag gallery.images[0].to_s %>
    <% end %>
    <div class="gallery__introduce">
      <span class="status"><%= gallery.public_status ? '公開中' : '非公開' %></span>
      <p><%= gallery.address %></p>
      <p><%= l gallery.travel.date %></p>
    </div>
  </div>
<% end %>
<%= paginate galleries, remote: true %>

app/views/users/edit.html.erb
<div class="main__field">
  <h1 class="page-name"> PROFILE EDIT</h1>

  <div class="user__form__box">
    <%= form_with model:@user, local:true do |f| %>
    <%= render 'layouts/errors', model: f.object %>
      <div class="user__form">
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="user__form">
        <%= f.text_field :name, class:"form" %>
      </div>
      <%= f.submit "UPDATE", class: "form__btn"%>
    <% end %>
  </div>

</div>

app/views/users/pagenate.js.erb
$('.gallery__index').html("<%= j(render "users/user_gallery_index", galleries: @galleries) %>");

app/views/users/show.html.erb
<div class="main__field">

  <h1 class="page-name">MY PAGE</h1>

  <div id="calendar_trigger">カレンダー</div>
  <div class="calendar_view">
    <%= render 'users/calendar'%>
  </div>

  <div class="user__wrap">
    <div class="user__left back">
      <h3>旅の作成</h3>

      <div class="travel__form">
        <%= form_with model: @travel, url: travels_path, remote:true do |f| %>
        <div class="error-messages"></div>
          <div class="form__box">
            <%= f.text_field :title, placeholder:"Please name your trip", class:"form" %>
            <%= f.date_field :date, class:"form date" %>
          </div>
          <%= f.submit "予定を考える", class:"btn" %>
        <% end %>
      </div>

      <div id="travel">
        <%= render 'travels/index', travels: @travels %>
        <%= paginate @travels %>
      </div>

    </div>

    <div class="user__right back">
      <h3>旅の共有</h3>
      <%= link_to new_gallery_path do %>
        <div class="travel__link__btn">先日の旅を共有する</div>
      <% end %>

      <div class="gallery__index">
        <%= render 'users/user_gallery_index', galleries: @galleries%>
      </div>
    </div>

  </div>
  <%= javascript_include_tag 'users/calendar_trigger' %>
</div>