config/routes.rb
Rails.application.routes.draw do
  get 'galleries/new'
  get 'galleries/edit'
  get 'galleries/index'
  root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    # 新規登録画面のリロード時のエラー防止
    get '/users', to: redirect("/users/sign_up")

    resources :users, only: [:show, :edit, :update]

    post '/galleries/new', to: 'galleries#new', as: 'new_gallery'
    resources :galleries, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
      get :marks, on: :collection
      resources :marks, only: [:create, :destroy]
    end

    patch 'travels/travel/:id/sort', to: 'travels#sort'
    resources :travels, only: [:create, :destroy, :index, :show] do
      resources :travel_plans, only: [:create, :update, :destroy]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord

  belongs_to :travel
  belongs_to :user
  has_many :marks, dependent: :destroy

  mount_uploaders :images, ImageUploader

  validates :text, presence: true
  validates :images, presence: true
  validates :public_status, inclusion: { in: [true, false] }
  validates :address, presence: true

  def marked_by?(user)
    marks.where(user_id: user.id).exists?
  end

end

app/models/mark.rb
class Mark < ApplicationRecord

  belongs_to :user
  belongs_to :gallery

  validates_uniqueness_of :gallery_id, scope: :user_id
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord

  belongs_to :user, optional: true

end

app/models/travel.rb
class Travel < ApplicationRecord

  belongs_to :user
  has_many :travel_plans, -> { order(position: :asc)}
  has_many :gallery, dependent: :destroy

  validates :title, presence: true, length:{maximum: 10}
  validates :date, presence: true
  
  def start_time
    self.date
  end
end

app/models/travel_plan.rb
class TravelPlan < ApplicationRecord

  belongs_to :travel
  acts_as_list scope: :travel

  validates :text, length:{maximum: 20}, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # emailのバリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter, :google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_many :travels, dependent: :destroy
  has_many :galleries
  has_many :marks, dependent: :destroy

  validates :name, length: { minimum: 1, maximum: 10 }
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }}

  attachment :profile_image

  def self.guest
    find_or_create_by!(name: "ゲストさん", email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end



  # SNS認証（登録済みuserかどうか）
  def self.from_omniauth(auth)
  sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create

  user = sns.user || User.where(email: auth.info.email).first_or_initialize(
    name: auth.info.name,
    email: auth.info.email
  )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image])
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!,except: [:show, :index]
  before_action :set_gallery, only: [:edit, :update, :show, :destroy]
  before_action :if_not_user_eq, only: [:edit, :update]
  before_action :set_own_travels, only: [:new, :update, :edit]


  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id = current_user.id
    if @gallery.save
      redirect_to gallery_path(@gallery)
    else
      @travels = current_user.travels.all
      render :new
    end
  end

  def edit
  end

  def update
    if @gallery.update(gallery_params)
      redirect_to gallery_path(@gallery.id)
    else
      render :edit
    end
  end

  def destroy
    if @gallery.user_id = current_user.id
      @gallery.destroy
      redirect_to user_path(current_user)
    else
      redirect_to gallery_path(@gallery)
    end
  end

  def marks
    user_marks = Mark.where(user_id: current_user).all
    @marks = user_marks.pluck(:gallery_id)
    @mark_galleries = Gallery.where(id: @marks).all.page(params[:page]).per(9)
  end

  def show
    @travel_plans = @gallery.travel.travel_plans.all
    @user = @gallery.travel.user
  end

  def index
    @galleries = Gallery.where(public_status: true).all.page(params[:page]).per(9)
  end


  private

  def set_own_travels
    @travels = current_user.travels.all
  end

  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  def if_not_user_eq
    if @gallery.user_id != current_user.id
      redirect_to gallery_path(@gallery)
    end
  end

  def gallery_params
    params.require(:gallery).permit(:travel_id, :text, :address, :latitude, :longitude, :public_status, { images: [] })
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_gallery, only: [:create, :destroy]

  def create
    Mark.create(user_id: current_user.id, gallery_id: @gallery.id)
    render 'marks/mark'
  end

  def destroy
    mark = @gallery.marks.find_by(user_id: current_user.id, gallery_id: @gallery.id)
    mark.destroy
    render 'marks/mark'
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:destroy, :show, :sort]

# user/show内

  def create
    @travel = Travel.new(travel_params)
    @travel.user_id = current_user.id

    @travel.save

    @travels = current_user.travels.all
    @selector = "#travel"
    @url = "travels/index"
    # travels/index.js.erbでindex.htmlを更新
    render 'travels/index'
  end

  def destroy
    @travel.destroy

    # 以下createと同じ
    @travels = current_user.travels.all
    @selector = "#travel"
    @url = "travels/index"
    # travels/index.js.erbでindex.htmlを更新
    render 'travels/index'
  end


# travels/show内

  def show
    @travel_plan = TravelPlan.new
  end

  # travels/_plansのposition更新
  def sort
    travel_plan = @travel.travel_plans[params[:from].to_i]
    travel_plan.insert_at(params[:to].to_i + 1)
    head :ok
  end


  private

  def set_travel
    @travel = Travel.find(params[:id])
  end

  def travel_params
    params.require(:travel).permit(:title, :start_time, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
    if @user != current_user
      redirect_to user_path(current_user)
    end
      @travel = @user.travels.new
      @travels = @user.travels.all.page(params[:page])
      @galleries = Gallery.where(user_id: @user.id).all.page(params[:page]).per(2)

      # pagenateの非同期
      respond_to do |format|
        format.html
        format.js { render :action => "pagenate" }
      end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def set_user
    @user = User.find(params[:id])

    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/travel_plans_helper.rb
module TravelPlansHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_box">
    <div id="error_messages">
      <ul>
        <% model.errors.full_messages.each do |message| %>
        <li id="error_item"><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice %>
　 <div class="alert alert-info"><%= flash[:notice] %>
     <button type="button" class="close" data-dismiss="alert"><i class="fas fa-times"></i></button>
   </div>
<% elsif alert %>
   <div class="alert alert-danger"><%= flash[:alert] %>
     <button type="button" class="close" data-dismiss="alert"><i class="fas fa-times"></i></button>
   </div>
<% end %>

app/views/layouts/_header.html.erb
<nav id="nav__menu">

  <ul class="nav__list">
  <% if user_signed_in? %>
    <li class="nav__item">
      <%= link_to 'MY PAGE', user_path(current_user.id), class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'GALLERY', galleries_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class:"nav__btn" %>
    </li>
  <% else %>
    <li class="nav__item">
      <%= link_to 'TOP', root_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'GALLERY', galleries_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'LOG IN',  new_user_session_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'FIRST VISIT', new_user_registration_path, class:"nav__btn" %>
    </li>
  <% end %>
  </ul>

</nav>

app/views/layouts/_menu.erb
<nav id="nav__menu">

  <ul class="nav__list">
  <% if user_signed_in? %>
    <li class="nav__item">
      <%= link_to 'MY PAGE', user_path(current_user.id), class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'GALLERY', galleries_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'BOOKMARK', marks_galleries_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class:"nav__btn" %>
    </li>
  <% else %>
    <li class="nav__item">
      <%= link_to 'TOP', root_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'GALLERY', galleries_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'LOG IN',  new_user_session_path, class:"nav__btn" %>
    </li>
    <li class="nav__item">
      <%= link_to 'FIRST VISIT', new_user_registration_path, class:"nav__btn" %>
    </li>
  <% end %>
  </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <header>
        <div class="logo_menu">
          <%= link_to root_path do %>
            <div id="logo"></div>
          <% end %>
          <div id="menu_trigger">▽▽▽</div>
        </div>

        <div class="user__profile">
          <% if user_signed_in?%>
            <%= link_to user_path(current_user.id) do %>
              <%= attachment_image_tag current_user, :profile_image, format: 'jpg', fallback: "no-image.jpg", id: "prf-img" %>
            <% end %>
            <div class="user__name">
               <p class="name"><%= current_user.name %> </p>
               <%= link_to edit_user_path(current_user.id) do %>
                 <i class="fas fa-edit"></i>
               <% end %>
            </div>
          <% end %>
        </div>
      </header>

      <%= render 'layouts/menu' %>

      <main>
        <%= yield %>
      </main>

      <footer>Sumi's Portfolio</footer>
    </div>

    <%= javascript_include_tag 'menu_trigger' %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>